version: '3.3'
services:
  database:
    image: "mysql:5.7"
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lportal
      - MYSQL_USER=dxpcloud
      - MYSQL_PASSWORD=dxpcloud
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --character-set-filesystem=utf8
    volumes:
      - type: volume
        source: database-data
        target: /var/lib/mysql
      - type: bind
        source: ./database
        target: /lcp-containe
  liferay:
    build: liferay/build/docker
    # If you have custom Dockerfile, uncomment below 3 lines and comment out the stock 'image' one above
    #image: "@liferay.workspace.lcp.liferay.image@_${WORKSPACE_PROJECT_NAME:-custom-dockerfile}"
    #build:
    #  context: ./@liferay.workspace.lcp.liferay.service.dir.name@

    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LIFERAY_JAVA_OPTS=-Xms2g -Xmx2g
      # ~ portal-ext.properties -> module.framework.properties.osgi.console=0.0.0.0:11311
      # We cannot set this in 'liferay/configs/local/portal-env.properties', see the file for details why
      - LIFERAY_MODULE_PERIOD_FRAMEWORK_PERIOD_PROPERTIES_PERIOD_OSGI_PERIOD_CONSOLE=0.0.0.0:11311
    ports:
      # Expose the Gogo shell port so that users can easily access it from Docker host
      - "127.0.0.1:11311:11311"
      - "127.0.0.1:10001:10001"
      - "127.0.0.1:10002:10002"
      - "127.0.0.1:8000:8000"
    volumes:
      - type: volume
        source: liferay-data
        target: /opt/liferay/data
      - type: bind
        source: ./liferay/data
        target: /docker-entrypoint-initlr.d
        consistency: delegated
      - type: bind
        source: ./liferay/build/docker/deploy
        target: /mnt/liferay/deploy
    depends_on:
      - database
      - search

  search:
    image: "liferaycloud/elasticsearch:7.17.1-4.1.6"
    # If you have custom Dockerfile, uncomment below 3 lines and comment out the stock 'image' one above
    #    image: "@liferay.workspace.lcp.search.image@_${WORKSPACE_PROJECT_NAME:-custom-dockerfile}"
    #    build:
    #      context: ./search

    environment:
      - LCP_PROJECT_ENVIRONMENT=local
      - LCP_SERVICE_SCALE=1
      - LCP_SERVICE_ID=search
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - type: bind
        source: ./search
        target: /lcp-container
      - type: volume
        source: search-data
        target: /data

  webserver:
    image: "liferaycloud/nginx:1.20.1-4.1.4"
    # If you have custom Dockerfile, uncomment below 3 lines and comment out the stock 'image' one above
    #    image: "@liferay.workspace.lcp.webserver.image@_${WORKSPACE_PROJECT_NAME:-custom-dockerfile}"
    #    build:
    #      context: ./webserver
    environment:
      - LCP_PROJECT_ENVIRONMENT=local
    ports:
      - "127.0.0.1:8080:80"
    links:
      - "liferay"
    volumes:
      - type: bind
        source: ./webserver
        target: /lcp-container
      - type: volume
        source: webserver-data
        target: /var/www/html
    depends_on:
      - liferay

volumes:
  liferay-data:
  database-data:
  search-data:
  webserver-data: